name: pyflow
version: 0.2.7
license: MIT  # todo: This appears to cause the `snapcraft` command to fail.
summary: A Python installation and dependency manager.
description: |
  Pyflow manages Python installations and dependencies.

  Goals: Make using and publishing Python projects as simple as possible. Actively
  managing Python environments shouldn't be required to use dependencies safely. We're attempting
  to fix each stumbling block in the Python workflow, so that it's as elegant
  as the language itself.

  You don't need Python or any other tools installed to use Pyflow.

  It runs standalone scripts in their
  own environments with no config, and project functions directly from the CLI.

grade: stable
confinement: classic

base: core18
parts:
  pyflow:
    plugin: rust
    rust-channel: stable
    source: .
    build-packages: ["pkg-config", "libssl-dev"]  # Required to prevent OpenSSL errors.

apps:
  pyflow:
    command: pyflow
    # Plugs not required for classic mode.
#    plugs: ["home", "removable-media", "network"]
